plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.18'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            mods {
                "${mod_id}" {
                    sourceSet project.sourceSets.main
                }
            }
        }

        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        gameTestServer {
            type = 'gameTestServer'
        }

        data {
            data()
            programArguments.addAll(
                    '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = 'CC-Tweaked'
        url = 'https://maven.squiddev.cc'
        content {
            includeGroup 'cc.tweaked'
        }
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "cc.tweaked:cc-tweaked-1.21.1-forge:${cc_tweaked_version}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version     : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version           : neo_version,
            neo_version_range     : neo_version_range,
            loader_version_range  : loader_version_range,
            mod_id                : mod_id,
            mod_name              : mod_name,
            mod_license           : mod_license,
            mod_version           : mod_version,
            mod_authors           : mod_authors,
            mod_description       : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'    : mod_id,
                'Specification-Vendor'   : mod_authors,
                'Specification-Version'  : '1',
                'Implementation-Title'   : project.name,
                'Implementation-Version' : project.jar.archiveVersion,
                'Implementation-Vendor'  : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'           : 'cc_utf8_compat.mixins.json'
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven { url "file://${project.projectDir}/mcmodsrepo" }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
